export const CREATE_COMMENT = 'CREATE_COMMENT'
export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const FETCH_POSTS = 'FETCH_POSTS'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const START_LOADING = 'START_LOADING'